#! /usr/bin/env bash

# This is a script to build LibreSymbols extensions.
#
# LibreSymbols
#
# Stefan Schmidhuber (stefan.schmidhuber@gmx.at)


print_help() {
  echo -e 'Usage: ./build [version]'
  echo -e 'Build a LibreSymbols extension of the given version or the latest'
  echo -e 'version if none is given. The optional  parameter "version" is a git tag.'  
  exit 0
}

get_tag() {
  if [ -z $1 ]; then
    TAG="last"
  else
    TAG=$1
  fi
  
  if [ $TAG = "last" ]; then
    if [ $(git tag -l | wc -l) -gt 0 ]; then
      TAG=$(git tag -l | tail -n 1)
      return 0
    else
      echo -e 'ERROR: can not find any tag'
      exit 1
    fi
  else
    for tmp in $(git tag -l); do
      if [ $tmp = $TAG ]; then
	return 0
      fi
    done
    echo 'ERROR: invalid tag "'$TAG'"'
    exit 1
  fi
}

build_extension() {
  TEMP_DIR=$(mktemp -d)
  WORKING_DIR=$(pwd)
  
  cp description.xml ${TEMP_DIR}/description.xml
  cp Paths.xcu ${TEMP_DIR}/Paths.xcu
  cp -r license ${TEMP_DIR}/license
  cp -r META-INF ${TEMP_DIR}/META-INF
  mkdir ${TEMP_DIR}/gallery
  cp gallery/en/* ${TEMP_DIR}/gallery/
  
  cd ${TEMP_DIR}  
  zip -rq LibreSymbols_${TAG}_en.zip *
  mv LibreSymbols_${TAG}_en.zip LibreSymbols_${TAG}_en.oxt
  cd ${WORKING_DIR}
  cp ${TEMP_DIR}/LibreSymbols_${TAG}_en.oxt .
  rm -r ${TEMP_DIR}
  
  return 0
}

# entry point

if [ ! -z $1 ]; then
  if [ $1 = "-h" ] || [ $1 = "-help" ] || [ $1 = "--help" ]; then
    print_help
  fi
fi

if [ $# -gt 1 ]; then
  echo -e 'ERROR: Invalid number of arguments.\n'
  print_help
fi

get_tag $1
echo -n 'building LibreSymbols version '$TAG' ... '

# remember current branch
BRANCH=$(git branch | grep "*" | cut -d" " -f 2)

git checkout $TAG &> /dev/null
build_extension
git checkout $BRANCH &> /dev/null

sleep 1
echo 'done'